### ISSUE TITLE
contact chamber and Experimental Apparatus

### ISSUE THREAD

**Issue by meera-shah** [AguaClara/Coagulant_nanoparticle_attachment_rate_characterization#11]
Are we keeping the contact chamber as a part of this experiment? Or are we analyzing particle behavior without it?

**Comment by monroews** [comment]
You are analyzing the nanoparticle behavior without the contact chamber. Your results may be used to inform the design of a contact chamber in the future. Now our goal is to understand the kinetics of the transport and attachment of nanoparticles to the clay.
